name: CD

on:
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        system: [ubuntu, darwin, win64]
        python: [3.6, 3.7, 3.8]
        exclude:
          - system: win64
            python: 3.8
        include:
          - system: rhel
            python: 2.7

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
    - name: Generate package
      id: package
      run: |
        version="${GITHUB_REF##*/*/}"
        echo ::set-output name=version::$version
        npm install
        npm run build -- $version ${{ matrix.python }}-${{ matrix.system }}
      env:
        TOKEN: ${{ secrets.TOKEN }}   
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: "GeodePackage-${{ steps.package.outputs.version }}-${{ matrix.system }}.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}    
