name: CI

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        system: [ubuntu, darwin, win64]
        python: [3.6, 3.7, 3.8]
        exclude:
          - system: win64
            python: 3.8
        include:
          - system: rhel
            python: 2.7

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
    - name: Compile
      run: |
        npm install
        npm run build -- version python${{ matrix.python }}-${{ matrix.system }}
      env:
        TOKEN: ${{ secrets.TOKEN }}   
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}    

  semantic-release:
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - uses: actions/checkout@v1
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
