name: CI

on: 
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
    - name: Compile
      run: |
        npm install
        npm run build -- version python${{ matrix.python }}-linux
      env:
        TOKEN: ${{ secrets.TOKEN }}   
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
    - name: Compile
      run: |
        npm install
        npm run build -- version python${{ matrix.python }}-win64
      env:
        TOKEN: ${{ secrets.TOKEN }}   
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  semantic-release:
    needs: [build-linux, build-windows]
    uses: Geode-solutions/actions/.github/workflows/release.yml@master
    secrets: inherit
